awesome_blog/config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

awesome_blog/app/models/AppStats.rb
class AppStats
  attr_reader :posts, :quotes

  def initialize(posts, quotes)
    @posts = posts
    @quotes = quotes
  end

  def posts_count
    return posts.length
  end

  def quotes_count
    return quotes.length
  end

  # NOTE: Returns the word count of all posts in one sum
  def posts_word_count
    total_words_in_posts = 0
    for post in posts
      total_words_in_posts += post.word_count
    end
    return total_words_in_posts
  end

  # NOTE: Returns the word count of all quotes in one sum
  def quotes_word_count
    total_words_in_quotes = 0
    for post in quotes
      total_words_in_quotes += post.word_count
    end
    return total_words_in_quotes
  end

  def total_word_count
    return posts_word_count + quotes_word_count
  end
end

awesome_blog/app/models/WordCounter.rb
module WordCounter
  def word_count
    # NOTE: Returns the number of words in the body attribute (should be a string)
    if self.body == nil
      return 0
    end
    return self.body.split.size
  end
end

awesome_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

awesome_blog/app/models/post.rb
class Post < ApplicationRecord
  include WordCounter, Publishable
end

awesome_blog/app/models/quote.rb
class Quote < ApplicationRecord
  include WordCounter, Publishable
end

awesome_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

awesome_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published_at)
    end
end

awesome_blog/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:body, :published_at)
    end
end

awesome_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

awesome_blog/app/helpers/posts_helper.rb
module PostsHelper
end

awesome_blog/app/helpers/quotes_helper.rb
module QuotesHelper
end

awesome_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

awesome_blog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

awesome_blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

awesome_blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.published_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

awesome_blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

awesome_blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

awesome_blog/app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

awesome_blog/app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

awesome_blog/app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.body %></td>
        <td><%= quote.published_at %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

awesome_blog/app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

awesome_blog/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @quote.body %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @quote.published_at %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>